-- MySQL Script generated by MySQL Workbench
-- Sat Jul  6 15:06:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Data
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Data` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Data` ;

-- -----------------------------------------------------
-- Table `Data`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Data`.`customers` (
  `CustomerID` INT NOT NULL,
  `AccountStatus` TEXT NULL DEFAULT NULL,
  `Age` INT NULL DEFAULT NULL,
  `CustomerTier` TEXT NULL DEFAULT NULL,
  `Gender` TEXT NULL DEFAULT NULL,
  `FirstName` TEXT NULL DEFAULT NULL,
  `LastName` TEXT NULL DEFAULT NULL,
  `CustomerSinceDate` INT NULL DEFAULT NULL,
  `City` TEXT NULL DEFAULT NULL,
  `StateProvince` TEXT NULL DEFAULT NULL,
  `Country` TEXT NULL DEFAULT NULL,
  `CountryISOCode` TEXT NULL DEFAULT NULL,
  `Latitude` DOUBLE NULL DEFAULT NULL,
  `Longitude` DOUBLE NULL DEFAULT NULL,
  `Name` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Data`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Data`.`employees` (
  `EMPLOYEEID` BIGINT NOT NULL,
  `EMPLOYEEACCESS` BIGINT NULL DEFAULT NULL,
  `Name` TEXT NULL DEFAULT NULL,
  `ACCESS` TEXT NULL DEFAULT NULL,
  `EMAIL` TEXT NULL DEFAULT NULL,
  `EmployeeGender` TEXT NULL DEFAULT NULL,
  `EmployeeDept` TEXT NULL DEFAULT NULL,
  `EmployeeBusinessUnit` TEXT NULL DEFAULT NULL,
  `EmployeeJobTitle` TEXT NULL DEFAULT NULL,
  `EMPLOYEEREGION` TEXT NULL DEFAULT NULL,
  `EmployeeCountry` TEXT NULL DEFAULT NULL,
  `EmployeeState` TEXT NULL DEFAULT NULL,
  `EmployeeCity` TEXT NULL DEFAULT NULL,
  `EmployeeJobClass` TEXT NULL DEFAULT NULL,
  `EmployeeManager` TEXT NULL DEFAULT NULL,
  `EmployeeEmploymentType` TEXT NULL DEFAULT NULL,
  `BAND` BIGINT NULL DEFAULT NULL,
  `PERFRATING` TEXT NULL DEFAULT NULL,
  `EmployeeEthnicity` TEXT NULL DEFAULT NULL,
  `DOB` BIGINT NULL DEFAULT NULL,
  `HIREDATE` BIGINT NULL DEFAULT NULL,
  `DPDate` BIGINT NULL DEFAULT NULL,
  `EmployeeActiveFlag` TEXT NULL DEFAULT NULL,
  `RECRUIT` TEXT NULL DEFAULT NULL,
  `SALARY` BIGINT NULL DEFAULT NULL,
  `TOTALCOMP` BIGINT NULL DEFAULT NULL,
  `OMITGROUP` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEEID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Data`.`ordermethod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Data`.`ordermethod` (
  `OrderMethodID` INT NOT NULL,
  `SalesOrderMethod` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`OrderMethodID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Data`.`ordersfact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Data`.`ordersfact` (
  `SalesOrderNumber` INT NOT NULL,
  `OrderDate` INT NULL DEFAULT NULL,
  `ShipDate` INT NULL DEFAULT NULL,
  `UnitsOrders` INT NULL DEFAULT NULL,
  `Revenue` INT NULL DEFAULT NULL,
  `Costs` DOUBLE NULL DEFAULT NULL,
  `GrossProfit` DOUBLE NULL DEFAULT NULL,
  `SalesForecast` INT NULL DEFAULT NULL,
  `Region` TEXT NULL DEFAULT NULL,
  `CustomerID` INT NOT NULL,
  `OrderMethodID` INT NOT NULL,
  `ProductID` INT NOT NULL,
  `EMPLOYEEID` BIGINT NOT NULL,
  PRIMARY KEY (`SalesOrderNumber`),
  INDEX `fk_ordersfact_customers_idx` (`CustomerID` ASC) VISIBLE,
  INDEX `fk_ordersfact_ordermethod1_idx` (`OrderMethodID` ASC) VISIBLE,
  INDEX `fk_ordersfact_employees1_idx` (`EMPLOYEEID` ASC) VISIBLE,
  CONSTRAINT `fk_ordersfact_customers`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `Data`.`customers` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordersfact_ordermethod1`
    FOREIGN KEY (`OrderMethodID`)
    REFERENCES `Data`.`ordermethod` (`OrderMethodID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordersfact_employees1`
    FOREIGN KEY (`EMPLOYEEID`)
    REFERENCES `Data`.`employees` (`EMPLOYEEID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Data`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Data`.`products` (
  `ProductID` INT NOT NULL,
  `ProductCategory` TEXT NULL DEFAULT NULL,
  `ProductSubcategory` TEXT NULL DEFAULT NULL,
  `ProductGroup` TEXT NULL DEFAULT NULL,
  `ProductVendor` TEXT NULL DEFAULT NULL,
  `ProductName` TEXT NULL DEFAULT NULL,
  `ProductModel` TEXT NULL DEFAULT NULL,
  `ProductUnitCost` DOUBLE NULL DEFAULT NULL,
  `ProductUnitPrice` DOUBLE NULL DEFAULT NULL,
  `ProductWeight` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ProductID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Data`.`ordersfact_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Data`.`ordersfact_has_products` (
  `ordersfact_SalesOrderNumber` INT NOT NULL,
  `products_ProductID` INT NOT NULL,
  PRIMARY KEY (`ordersfact_SalesOrderNumber`, `products_ProductID`),
  INDEX `fk_ordersfact_has_products_products1_idx` (`products_ProductID` ASC) VISIBLE,
  INDEX `fk_ordersfact_has_products_ordersfact1_idx` (`ordersfact_SalesOrderNumber` ASC) VISIBLE,
  CONSTRAINT `fk_ordersfact_has_products_ordersfact1`
    FOREIGN KEY (`ordersfact_SalesOrderNumber`)
    REFERENCES `Data`.`ordersfact` (`SalesOrderNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordersfact_has_products_products1`
    FOREIGN KEY (`products_ProductID`)
    REFERENCES `Data`.`products` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
